version: '3'

volumes:
  pg_data:
  static_volume:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: juliavkom/taski_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    image: juliavkom/taski_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: juliavkom/taski_gateway:latest
    volumes:
      - static_volume:/staticfiles/

    ports:
      - 8000:80